### ISSUE TITLE
Code injection in web page

### ISSUE THREAD

**Issue by benjivrd** [csakis/basic-react-chrome-extension#1]
Hi , 
Thanks for sharing this project.
I am trying to inject the Material UI lib in a web page.
Could you advise how to do it ?

Currently your projects works well in the menu popup.html
Also when I try to inject Material UI in the current viewed web page, it doesn t work.

Thanks for your help

**Comment by csakis** [comment]
If you need to inject code into the webpage that the user is currently on, you need to modify the [content.js](https://github.com/csakis/basic-react-chrome-extension/blob/master/src/content.js) file.
It's not straightforward, since you cannot predict what that page would be, unless you have a specific use case. 
You will also need to extend the app's permissions in the [manifest.json](url).

**Comment by benjivrd** [comment]
Hi, thanks for your answer. 
I did what I wanted to do, I had to modify the frame component and manifest file 
have a Good day.
